version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/ads_platform?sslmode=disable
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - postgres
      - redis
    command: air

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ads_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  migrate:
    image: migrate/migrate
    networks:
      - default
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:password@postgres:5432/ads_platform?sslmode=disable", "up"]
    depends_on:
      - postgres

volumes:
  postgres_data: