services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - go-modules:/go/pkg/mod
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOPATH=/go
      - DATABASE_URL=postgres://postgres:password@postgres:5432/vibe_marketing?sslmode=disable
      - REDIS_URL=redis://redis:6379
    networks:
      - vibe-network

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: vibe_marketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../pkg/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - vibe-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - vibe-network

volumes:
  postgres-data:
  go-modules:

networks:
  vibe-network:
    driver: bridge